apiVersion: apps/v1
kind: Deployment
metadata:
  name: finance-service
  labels:
    app: finance-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finance-service
  template:
    metadata:
      labels:
        app: finance-service
    spec:
      containers:
      - name: finance-service
        image: "390403864598.dkr.ecr.us-east-1.amazonaws.com/finance-service:9"
        ports:
        - containerPort: 8080  # Port exposed by your gateway container
      initContainers:
      - name: init-eureka
        image: "390403864598.dkr.ecr.us-east-1.amazonaws.com/finance-service:9"
        command: ['sh', '-c', 'until nslookup eureka-server.default.svc.cluster.local; do echo waiting for Eureka; sleep 2; done;']
      