apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
  namespace: default
spec:
  metrics:
    - name: success-rate
      successCondition: result > 0.9
      failureCondition: result < 0.5
      provider:
        prometheus:
          address: http://prometheus.istio-system.svc.cluster.local
          query: |
            sum(rate(http_requests_total{status=~"2.*"}[1m])) / sum(rate(http_requests_total[1m]))